### ISSUE TITLE
iPython craches when run as PID 1

### ISSUE THREAD

**Issue by soltysh** [openshift/sti-python#77]
There's a known issue with iPython we might want to address somehow in the base image. The problem is that when running ipython with PID 1 (iow. using docker) it'll crash. You need a process that will handle that for you, as described [here](http://jupyter-notebook.readthedocs.org/en/latest/public_server.html#docker-cmd). 

@bparees @rhcarvalho @GrahamDumpleton wdyt

**Comment by GrahamDumpleton** [comment]
FWIW, I integrated ``tini`` into my Docker base images and thus my S2I builders already. :-)

I pull various source packages and compile from source code so don't have an issue with that, but if you have the restriction of only being able to use official packages that is likely going to be a problem unless there is something equivalent in package repositories already.

**Comment by bparees** [comment]
@soltysh what's the likelihood that iPython gets fixed?  this doesn't sound like a complexity we want to add to our images by default (and we'd need an rpm package of tini, if one doesn't exist, so we'd probably need the SCL team to adopt it)

**Comment by GrahamDumpleton** [comment]
Reality is that no one would use the Red Hat S2I images if they want to build a Docker image for IPython. So is not a big deal.

**Comment by soltysh** [comment]
I think @GrahamDumpleton answered that question already.

**Comment by bparees** [comment]
Given that, is there a compelling reason to keep this open?

**Comment by soltysh** [comment]
I think we can close it. It'll be kept here for reference for other folks struggling with similar problems.

**Comment by bparees** [comment]
Thanks @soltysh

**Comment by soltysh** [comment]
Thank @GrahamDumpleton he pointed me to that problem :smile:

**Comment by GrahamDumpleton** [comment]
I should have clarified that although no one will use this image for IPython, they will use the Tornado WSGI server and Tornado ASYNC server, Waitress WSGI server, plus others such as the Python standard library HTTP server. None of these will handle properly the pid 1 zombie reading and so eventually will crap out due to memory usage issues, or confusion due to reparenting of processes (as is case for IPython).

I will be posting a blog post about the issue as part of my series on porting IPython to Docker/OpenShift, highlighting how these other commonly used Python web servers can fail.

**Comment by soltysh** [comment]
@GrahamDumpleton that sounds perfect, can you please post a link to it in this issue?

**Comment by GrahamDumpleton** [comment]
http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html
